### ISSUE TITLE
A question about input image size

### ISSUE THREAD

**Issue by e0jun** [JAYATEJAK/S3C#2]
Hello author,
Thanks for the release of the code of your paper. I love your work.

Should I change the current "data.view(-1, 3, 32, 32)" to the input image size of the target dataset when implementing your code? (e.g., 84 for miniIN)

Thank you :-)

**Comment by JAYATEJAK** [comment]
Hello thanks for intersted in my work.
For CIFAR100 "data.view(-1, 3, 32, 32)"
For CUB200 "data.view(-1, 3, 224, 224)"
For Imagenet "data.view(-1, 3, 84, 84)"

**Comment by e0jun** [comment]
Thank you for your quick reply!

Is there any other code that we have to change when we change the dataset from CIFAR100 to other datasets (e.g., miniIN or CUB200)? 
This code might be for CIFAR with ResNet20 (output dimension size is 64).
So, when changing ResNet20 to ResNet18, I think there are some codes requiring changing 64 to 512.

Thank you:)

**Comment by RiyaVerma02** [comment]
Hi @JAYATEJAK ,

Great work.
Could you kindly confirm changing of code for output dimension also? @e0jun point makes sense.

**Comment by JAYATEJAK** [comment]
Hi @e0jun and @RiyaVerma02 , you don't need to change any code. It will take [ResNet20](https://github.com/JAYATEJAK/S3C/blob/main/models/s3c/Network.py) (line 44) for CIFAR (d=64), and ResNet18 for CUB and miniImangeNet (d=512). Additionally, when calculating prototypes in [helper.py](https://github.com/JAYATEJAK/S3C/blob/main/models/s3c/helper.py), it will be computed through dim=0, so you shouldn't encounter any issues

**Comment by RiyaVerma02** [comment]
Got it, Thank you for prompt reply. Great help.
