### ISSUE TITLE
RuntimeError for (CUB200): stack expects each tensor to be equal size, but got [100, 512] at entry 0 and [64, 512] at entry 28

### ISSUE THREAD

**Issue by RiyaVerma02** [JAYATEJAK/S3C#3]
Hi @JAYATEJAK,

Can you please help with the error, while running the bash script for cub200 dataset. Encountering this error:

**File "/data/Riya/S3C/S3C-main/models/s3c/helper.py", line 333, in save_features
data_features = torch.stack(data_features).view(-1, 64)
RuntimeError: stack expects each tensor to be equal size, but got [100, 512] at entry 0 and [64, 512] at entry 28**

In dataloader (cub200.py), I tried to change  transforms.Resize(img_size) to transforms.Resize((img_size, img_size)) to deal with images of different sizes, but the error still persits.

**Comment by JAYATEJAK** [comment]
Hi, 64 indicates the feature dimension, please keep 512 for while running script on CUB and imagenet datasets.

**Comment by RiyaVerma02** [comment]
Hello @JAYATEJAK,

Yes, but with that also getting the same error:

  **File "/data/Riya/S3C/S3C-main/models/s3c/helper.py", line 333, in save_features
    data_features = torch.stack(data_features).view(-1, 512)
RuntimeError: stack expects each tensor to be equal size, but got [100, 512] at entry 0 and [64, 512] at entry 28**

This error is only coming for CUB200 dataset, imagenet works fine.

**Comment by JAYATEJAK** [comment]
Hi, It is happening due to the unequal number of images for each class. You can try out any other torch-inbuilt functions to make them stack.
