### ISSUE TITLE
Results are not reproducible 

### ISSUE THREAD

**Issue by Learning-Enthu** [JAYATEJAK/S3C#4]
[](url)Hi @JAYATEJAK, excellent work using stochastic classifier. 
However, When I am running the code, accuracy/harmonic mean for either of the datasets is not matching with the ones reported in the paper.
I have used the same environment (batch-size, learning rate etc)

**For cifar100:**

Overall cumulative accuracy: 50.53999873250723, after agg: 54.139998642727726
Novel classes cumulative accuracy: 25.974999349564314, after agg: 34.54999889712781
Files already downloaded and verified
session: 0 test accuracy: 66.9166649878025, after agg: **67.19999847312769**
session: 1 test accuracy: 27.39999912679195, after agg: 38.399998247623444
session: 2 test accuracy: 21.99999950826168, after agg: 28.1999995931983
session: 3 test accuracy: 21.799999177455902, after agg: 29.199999272823334
session: 4 test accuracy: 26.199999749660492, after agg: 32.79999911785126
session: 5 test accuracy: 25.999999642372128, after agg: 33.79999905824661
session: 6 test accuracy: 28.59999924898148, after agg: 35.39999842643738
session: 7 test accuracy: 31.799998581409454, after agg: 42.99999922513962
session: 8 test accuracy: 23.99999976158142, after agg: 35.599998235702515
Task wise Harmonic mean is : 27.48308586888903, agg: 35.957127526293206
Harmonic mean between old and new classes : 38.5619747028958, agg: **48.00984796352398**
protos, radius torch.Size([100, 64]) 0.2682569628945948

------------------------------------------------------------------------------------------------------------------------
**For cub200:**

Overall cumulative accuracy: 54.06456186339772, after agg: 56.71129725102722
Novel classes cumulative accuracy: 36.15555480122566, after agg: 42.19999944170316
session: 0 test accuracy: 73.23060128195532, after agg: **72.57542908191681**
session: 1 test accuracy: 42.919831474622086, after agg: 51.94092790285746
session: 2 test accuracy: 30.81226001183192, after agg: 34.77777739365895
session: 3 test accuracy: 23.877550661563873, after agg: 29.891155163447063
session: 4 test accuracy: 39.33333158493042, after agg: 52.333332101504006
session: 5 test accuracy: 26.877550035715103, after agg: 28.217685967683792
session: 6 test accuracy: 38.51515154043834, after agg: 44.545453786849976
session: 7 test accuracy: 32.975943883260086, after agg: 31.955325106779735
session: 8 test accuracy: 35.52631537119548, after agg: 41.87719225883484
session: 9 test accuracy: 44.121211767196655, after agg: 53.34848463535309
session: 10 test accuracy: 42.33333269755046, after agg: 46.99999888737996
Task wise Harmonic mean is : 36.10781631468557, agg: 41.13219089652484
Harmonic mean between old and new classes : 49.5131919344956, agg: **55.022080762858316**
protos, radius torch.Size([200, 512]) 0.4308898191906074

Paper:
Even session 0 accuracy is not matching as reported in paper: 80.62
**S3C (Ours) 80.62 77.55 73.19 68.54 68.05 64.33 63.58 62.07 60.61 59.79 58.95** 
-------------------------------------------------------------------------------------------------------------------

**For imagenet:**

Overall cumulative accuracy: 48.74999884143472, after agg: 51.339998973533504
Novel classes cumulative accuracy: 17.54999958910048, after agg: 21.849999614059925
session: 0 test accuracy: 69.54999834299088, after agg: 70.99999854651588
session: 1 test accuracy: 14.399999603629112, after agg: 17.799999602138996
session: 2 test accuracy: 14.199999868869781, after agg: 21.399999260902405
session: 3 test accuracy: 23.599999248981476, after agg: 30.799999944865704
session: 4 test accuracy: 12.59999994188547, after agg: 14.799999445676804
session: 5 test accuracy: 11.799999624490738, after agg: 16.799999624490738
session: 6 test accuracy: 13.399999439716339, after agg: 18.599999845027924
session: 7 test accuracy: 31.199999451637268, after agg: 32.599999755620956
session: 8 test accuracy: 19.199999533593655, after agg: 21.999999433755875
Task wise Harmonic mean is : 17.32467244294403, agg: 22.143218220594903
Harmonic mean between old and new classes : 28.365250496811857, agg: **33.969920891821246**
protos, radius torch.Size([100, 512]) 0.11957196929414952

Could you please to understand that why it may be happening so?

**Comment by JAYATEJAK** [comment]
Hi @Learning-Enthu 
For Cifar100, you can observe -> Overall cumulative accuracy: 50.53999873250723, after agg: 54.139998642727726
after aggregation it is 54.13, similar numbers we reported in paper (Fig3).

You might confused with overall cumulative accuracy first number (50.53) -> there testing is happening only with rotation0 classifiers.

I will suggest you to see carefully Eq.7 in paper and the **testagg** function in helper file to get more clarity -> https://github.com/JAYATEJAK/S3C/blob/main/models/s3c/helper.py

**Comment by YvoGao** [comment]
> Hi @JAYATEJAK, excellent work using stochastic classifier. However, When I am running the code, accuracy/harmonic mean for either of the datasets is not matching with the ones reported in the paper. I have used the same environment (batch-size, learning rate etc)
> 
> **For cifar100:**
> 
> Overall cumulative accuracy: 50.53999873250723, after agg: 54.139998642727726 Novel classes cumulative accuracy: 25.974999349564314, after agg: 34.54999889712781 Files already downloaded and verified session: 0 test accuracy: 66.9166649878025, after agg: **67.19999847312769** session: 1 test accuracy: 27.39999912679195, after agg: 38.399998247623444 session: 2 test accuracy: 21.99999950826168, after agg: 28.1999995931983 session: 3 test accuracy: 21.799999177455902, after agg: 29.199999272823334 session: 4 test accuracy: 26.199999749660492, after agg: 32.79999911785126 session: 5 test accuracy: 25.999999642372128, after agg: 33.79999905824661 session: 6 test accuracy: 28.59999924898148, after agg: 35.39999842643738 session: 7 test accuracy: 31.799998581409454, after agg: 42.99999922513962 session: 8 test accuracy: 23.99999976158142, after agg: 35.599998235702515 Task wise Harmonic mean is : 27.48308586888903, agg: 35.957127526293206 Harmonic mean between old and new classes : 38.5619747028958, agg: **48.00984796352398** protos, radius torch.Size([100, 64]) 0.2682569628945948
> 
> **For cub200:**
> 
> Overall cumulative accuracy: 54.06456186339772, after agg: 56.71129725102722 Novel classes cumulative accuracy: 36.15555480122566, after agg: 42.19999944170316 session: 0 test accuracy: 73.23060128195532, after agg: **72.57542908191681** session: 1 test accuracy: 42.919831474622086, after agg: 51.94092790285746 session: 2 test accuracy: 30.81226001183192, after agg: 34.77777739365895 session: 3 test accuracy: 23.877550661563873, after agg: 29.891155163447063 session: 4 test accuracy: 39.33333158493042, after agg: 52.333332101504006 session: 5 test accuracy: 26.877550035715103, after agg: 28.217685967683792 session: 6 test accuracy: 38.51515154043834, after agg: 44.545453786849976 session: 7 test accuracy: 32.975943883260086, after agg: 31.955325106779735 session: 8 test accuracy: 35.52631537119548, after agg: 41.87719225883484 session: 9 test accuracy: 44.121211767196655, after agg: 53.34848463535309 session: 10 test accuracy: 42.33333269755046, after agg: 46.99999888737996 Task wise Harmonic mean is : 36.10781631468557, agg: 41.13219089652484 Harmonic mean between old and new classes : 49.5131919344956, agg: **55.022080762858316** protos, radius torch.Size([200, 512]) 0.4308898191906074
> 
> ## Paper:
> Even session 0 accuracy is not matching as reported in paper: 80.62
> **S3C (Ours) 80.62 77.55 73.19 68.54 68.05 64.33 63.58 62.07 60.61 59.79 58.95**
> **For imagenet:**
> 
> Overall cumulative accuracy: 48.74999884143472, after agg: 51.339998973533504 Novel classes cumulative accuracy: 17.54999958910048, after agg: 21.849999614059925 session: 0 test accuracy: 69.54999834299088, after agg: 70.99999854651588 session: 1 test accuracy: 14.399999603629112, after agg: 17.799999602138996 session: 2 test accuracy: 14.199999868869781, after agg: 21.399999260902405 session: 3 test accuracy: 23.599999248981476, after agg: 30.799999944865704 session: 4 test accuracy: 12.59999994188547, after agg: 14.799999445676804 session: 5 test accuracy: 11.799999624490738, after agg: 16.799999624490738 session: 6 test accuracy: 13.399999439716339, after agg: 18.599999845027924 session: 7 test accuracy: 31.199999451637268, after agg: 32.599999755620956 session: 8 test accuracy: 19.199999533593655, after agg: 21.999999433755875 Task wise Harmonic mean is : 17.32467244294403, agg: 22.143218220594903 Harmonic mean between old and new classes : 28.365250496811857, agg: **33.969920891821246** protos, radius torch.Size([100, 512]) 0.11957196929414952
> 
> Could you please to understand that why it may be happening so?

I got the similar result, do you fix it out?
